Documents
enssol/web-app pull request #15
Opened 2024-11-26 01:57 UTC by bwork005

Changes made in the Readme and Templates

2024-11-26 03:06 UTC, enveng-group requested changes
@bwork005 please go through the files and make changes addressing all my comments from the code review.

2024-11-26 05:41 UTC, enveng-group requested changes
@bwork005 nearly there. Please also ensure you are checking for `markdown-linting` errors, warning and problems in VS Studio Code.

2024-11-26 05:41 UTC, enveng-group commented on README.md
> +This project is licensed under the [[LICENSE]AGPLv3](LICENSE). Please review the LICENCE file for details on usage and distribution.
@bwork005 did you check whether this hyperlink works?

2024-11-26 05:41 UTC, enveng-group commented on README.md
> +Lead Developer: [Your Name](https://github.com/your-username)
@bwork005 line is incomplete, please revisit.

2024-11-26 05:41 UTC, enveng-group commented on README.md
> +Project Maintainer: [Project Maintainer Name](https://github.com/maintainer-username).
@bwork005 line is incomplete, please revisit

2024-11-26 05:41 UTC, enveng-group commented on docs/CONTACT.md
> +- **GitHub Discussions**: Join the conversation on our [GitHub Discussions] page.
@bwork005 did you check whether these links work?

2024-11-26 05:41 UTC, enveng-group commented on docs/CONTRIBUTORS.md
@bwork005 where is you?

2024-11-26 05:41 UTC, enveng-group commented on docs/INSTALL.md
@bwork005 delete line 8 to 20

2024-11-26 06:04 UTC, bwork005 commented on docs/CONTACT.md
> +- **GitHub Discussions**: Join the conversation on our [GitHub Discussions] page.
Yes! Changed it now.

2024-11-26 07:26 UTC, enveng-group requested changes
@bwork005 Please review all feedback and mark as resolved to track code changes.

- See: [Commenting on Pull Requests] (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)

2024-11-26 07:26 UTC, enveng-group commented on README.md
> +For more information, refer to our [[CONTRIBUTING.md]CONTRIBUTING.md](CONTRIBUTING.md) file.
@bwork005  Please check how line 171 appears when you preview the file. Are you sure we need to repeat `CONTRIBUTING.md` twice?

2024-11-26 07:26 UTC, enveng-group commented on README.md
> +This project is licensed under the [[LICENSE]AGPLv3](LICENSE). Please review the LICENCE file for details on usage and distribution.
@bwork005 Are you sure the Markdown syntax is correct for line 177 to enclose square brackets within square brackets for the hyperlink?

- See [Markdown Links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)

2024-11-26 07:26 UTC, enveng-group commented on docs/CONTACT.md
> +- **[enveng-group](https://github.com/enveng-group)** - enveng-group agallo
@bwork005 why are you repeating `enveng-group` and why are you using `agallo`?

2024-11-26 07:26 UTC, enveng-group commented on docs/CONTACT.md
> +- **[enveng-group](https://github.com/bwork005)** - enveng-group bwork005
@bwork005 Why are you using `enveng-group` as the display name for the link to your Github profile?

Why are you repeating the use `enveng-group` at the end, along with repeating your Github handle in plain text?

Did you preview this page before submitting your commit?

- See [Mentioning People and Teams](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams)

2024-11-26 08:22 UTC, bwork005 commented on .markdown.json
Done!

2024-11-26 12:38 UTC, enveng-group requested changes
@bwork005 nearly there. Please double check hyperlinks before resolving.

2024-11-26 12:38 UTC, enveng-group commented on README.md
> +Lead Developer: [Adrian Agallo](agallo@enveng-group.com.au)
@bwork005 my surname is incorrect. The correct surname to use is "Gallo".

2024-11-26 12:38 UTC, enveng-group commented on README.md
> +Project Maintainer: [Adrian Agallo](agallo@enveng-group.com.au)
@bwork005 my surname is incorrect. The correct surname to use is "Gallo".

2024-11-26 12:38 UTC, enveng-group commented on SUPPORT.md
> +- **User Guide**: Detailed instructions on how to use Web-App repo can be found in the CONTRIBUTING.md (develop/CONTRIBUTING.md).
@bwork005 double-check please, whether the link to the CONTRIBUTING file works?

2024-11-26 12:38 UTC, enveng-group commented on SUPPORT.md
> +We welcome contributions to Web-App! If you would like to contribute, please read our [Contributing Guidelines](CONTRIBUTING) for more information on how to get started.
@bwork005 double-check please, whether the link to the CONTRIBUTING file works?

2024-11-26 12:38 UTC, enveng-group commented on docs/CONTACT.md
> +For support, please our [Support Page](../SUPPORT.md).
@bwork005 double-check please, whether the link to the SUPPORT file works?

2024-11-26 13:27 UTC, bwork005 commented on SUPPORT.md
> +- **User Guide**: Detailed instructions on how to use Web-App repo can be found in the CONTRIBUTING.md (develop/CONTRIBUTING.md).
All the links are working.

2024-11-27 01:20 UTC, enveng-group approved these changes

2024-11-27 01:53 UTC, merged